# Generated by Django 4.2.4 on 2023-10-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
